// <auto-generated />
namespace WeBStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addDateOfBirthOfCustmer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDateOfBirthOfCustmer));
        
        string IMigrationMetadata.Id
        {
            get { return "201704041243393_addDateOfBirthOfCustmer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
